kind: DestinationRule
apiVersion: networking.istio.io/v1
metadata:
  namespace: devops
  name: devops-yellow-clusterip
  labels:
    kiali_wizard: request_routing
  annotations: ~
spec:
  host: devops-yellow-clusterip.devops.svc.cluster.local
  subsets:
  - name: old
    labels:
      version: 1.0.0
  trafficPolicy: ~
---
kind: VirtualService
apiVersion: networking.istio.io/v1
metadata:
  namespace: devops
  name: devops-yellow-clusterip
  labels:
    kiali_wizard: request_routing
spec:
  http:
  - route:
    - destination:
        host: devops-yellow-clusterip.devops.svc.cluster.local
        subset: old
      weight: 100
    fault:
      #delay:
      #  percentage:
      #    value: 100
      #  fixedDelay: 5s
      abort:
        percentage:
          value: 100
        httpStatus: 503
  hosts:
  - devops-yellow-clusterip.devops.svc.cluster.local
  gateways: ~
