kind: DestinationRule
apiVersion: networking.istio.io/v1
metadata:
  namespace: devops
  name: devops-white-clusterip
  labels:
    kiali_wizard: request_routing
  annotations: ~
spec:
  host: devops-white-clusterip.devops.svc.cluster.local
  subsets:
  - name: old
    labels:
      version: 1.0.0
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 1m
      baseEjectionTime: 1m
---
kind: VirtualService
apiVersion: networking.istio.io/v1
metadata:
  namespace: devops
  name: devops-white-clusterip
  labels:
    kiali_wizard: request_routing
spec:
  http:
  - route:
    - destination:
        host: devops-white-clusterip.devops.svc.cluster.local
        subset: old
      weight: 100
  hosts:
  - devops-white-clusterip.devops.svc.cluster.local
  gateways: ~